//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PointOfSales.Globalization.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Translations {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translations() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("PointOfSales.Globalization.Resources.Translations", typeof(Translations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string CreatingDirectoryLabel {
            get {
                return ResourceManager.GetString("CreatingDirectoryLabel", resourceCulture);
            }
        }
        
        public static string LoadingLabel {
            get {
                return ResourceManager.GetString("LoadingLabel", resourceCulture);
            }
        }
        
        public static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
        
        public static string SignInMessage {
            get {
                return ResourceManager.GetString("SignInMessage", resourceCulture);
            }
        }
        
        public static string EnterYourUserName {
            get {
                return ResourceManager.GetString("EnterYourUserName", resourceCulture);
            }
        }
        
        public static string EnterYourPassword {
            get {
                return ResourceManager.GetString("EnterYourPassword", resourceCulture);
            }
        }
        
        public static string LoginLabel {
            get {
                return ResourceManager.GetString("LoginLabel", resourceCulture);
            }
        }
        
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        public static string LocationCodeLabel {
            get {
                return ResourceManager.GetString("LocationCodeLabel", resourceCulture);
            }
        }
        
        public static string ConnectivityLabel {
            get {
                return ResourceManager.GetString("ConnectivityLabel", resourceCulture);
            }
        }
        
        public static string ConnectedLabel {
            get {
                return ResourceManager.GetString("ConnectedLabel", resourceCulture);
            }
        }
        
        public static string DisconnectedLabel {
            get {
                return ResourceManager.GetString("DisconnectedLabel", resourceCulture);
            }
        }
        
        public static string WelcomeBackLabel {
            get {
                return ResourceManager.GetString("WelcomeBackLabel", resourceCulture);
            }
        }
        
        public static string PleaseChooseAnActionToContinue {
            get {
                return ResourceManager.GetString("PleaseChooseAnActionToContinue", resourceCulture);
            }
        }
    }
}
